Add option to customize generated cell keys
sondrele/gatsby-source-google-spreadsheet pull request #3
Opened 2019-07-05 15:12 UTC by Artsu

Added option to customize each cell's key as sometimes the camelcase library does a poor job guessing the correct key. For example special characters and letters outside ascii might get switched to underscore.

2019-07-07 20:33 UTC, sondrele requested changes
Thanks for the contribution! Will release once the typo in the readme has been fixed :smiley:

2019-07-07 20:33 UTC, sondrele commented on README.md
> +    mapValue: key => key === 'ääöö' ? 'aaoo' : key
This should be `mapKey` :smiley:

2019-07-08 09:01 UTC, Artsu commented on README.md
> +    mapValue: key => key === 'ääöö' ? 'aaoo' : key
Yeah it should 😅 Fixed it now!

2019-08-16 08:07 UTC, sondrele commented
@Artsu Sorry for the late reply, I've been on vacation and quite busy with other things lately.
It also turns out I already released version 2 of this source plugin a while ago, but forgot to update the master branch (I had a vague resemblance of working on something like this, but I completely missed it while vacationing). Thus, your changes can be solved by configuring and implementing the `mapNode` option instead.
Really sorry for the inconvenience and for wasting your time! :(

2019-08-16 08:07 UTC, closed without merging